/*
  PaulWrites portfolio data
  -------------------------
  Add new work by copying one object below and changing its values.

  The familiar five fields are enough: title, description, link, date, tags.
  The richer current records also use optional id, type, publisher, summary,
  url, linkLabel, datePrecision, and featured fields. Both shapes work.
  The portfolio sorts and paginates this list automatically.
*/
window.PAULWRITES_ITEMS = [
  {
    id: "phytoremediation-habs-feasibility-review",
    title: "Phytoremediation of North American Harmful Algal Blooms Under Long-Term Feasibility Constraints",
    date: "2026-01-01",
    datePrecision: "year",
    type: "Literature review",
    publisher: "Nazareth University",
    summary: "A feasibility-centered review comparing water hyacinth, star duckweed, and parrot’s feather for bloom suppression and cyanotoxin removal.",
    projectContext: "Completed at Nazareth University, this literature review compared aquatic macrophytes across remediation performance, cyanotoxin relevance, ecological risk, regional fit, and long-term feasibility. Paul’s role was to synthesize a dispersed scientific literature into a cautious, usable conclusion.",
    readingMinutes: 22,
    image: "public/images/work/duckweed.webp",
    imageAlt: "Duckweed covering the surface of a wetland stream",
    tags: ["Environmental Science", "Research", "Scientific Communication"],
    url: "public/downloads/phytoremediation-habs-literature-review.pdf",
    linkLabel: "Read the research paper",
    featured: false
  },
  {
    id: "noovie-trivia-levels-up",
    title: "Noovie Trivia Gets Faster With Fresh Content and New 1v1 Battles",
    date: "2026-01-01",
    datePrecision: "year",
    type: "Product update article",
    publisher: "Workinman Interactive",
    summary: "A concise release story turning performance improvements, QR-based challenges, and new social features into an audience-centered update.",
    projectContext: "This release story translated a dense product brief—faster performance, shorter load times, fresh questions, QR-based match joining, 1v1 battles, and expanded MotionPicks comparisons—into a concise update for movie fans. Paul worked within Workinman’s studio process, using priorities and feedback from product stakeholders, editors, executives, and the creative team to keep the copy accurate, energetic, and centered on what changed for players.",
    readingMinutes: 4,
    image: "public/images/work/noovie-trivia-levels-up.webp",
    imageAlt: "Two Noovie Trivia players holding phones beside a one-versus-one game graphic",
    tags: ["Client Work", "Technology", "Interactive Media", "B2B"],
    url: "https://workinman.com/noovie-trivia-levels-up/",
    linkLabel: "Read on Workinman",
    featured: false
  },
  {
    id: "trade-show-booth-gamification",
    title: "What Trade Show Booths Can Learn from Video Games",
    date: "2025-12-03",
    type: "B2B industry article",
    publisher: "Workinman Interactive",
    summary: "A case-led explanation of how participatory demos, social momentum, analytics, and iteration can turn a booth into an experience.",
    projectContext: "Written for event marketers and teams planning experiential booths, this article moves from attention and learning to retention, social momentum, analytics, and rapid iteration. Paul shaped studio examples—including VR product demonstrations, venue-wide scavenger hunts, live trivia, and projection work—into a practical B2B argument, working with Workinman contributors who supplied project context, examples, editorial direction, and review.",
    readingMinutes: 5,
    image: "public/images/work/trade-show-gamification.webp",
    imageAlt: "Colorful game and event graphics representing a gamified trade show experience",
    tags: ["Client Work", "B2B", "Interactive Media", "SEO & Content"],
    url: "https://workinman.com/trade-show-booth-gamification/",
    linkLabel: "Read on Workinman",
    featured: false
  },
  {
    id: "why-entrepreneurship-became-a-trend",
    title: "Why Entrepreneurship Became a Trend—and How Dropshipping Hype Leaves People Broke",
    date: "2025-06-26",
    type: "Article",
    publisher: "LinkedIn",
    summary: "A closer look at the gap between entrepreneurial hype and the systems required to build a durable business.",
    projectContext: "An independently researched commentary article using dropshipping culture as a lens for the difference between promotional claims and the operational work behind a sustainable freelance or small-business practice.",
    readingMinutes: 5,
    image: "public/images/work/writer.webp",
    imageAlt: "Black-and-white photograph of a writer working at a desk",
    tags: ["Freelancing", "SEO & Content"],
    url: "https://www.linkedin.com/pulse/why-entrepreneurship-became-trendand-how-dropshipping-paul-shannon-2dvcc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "bonn-2025-climate-negotiations",
    title: "The Climate Negotiations You Haven’t Heard Of — Why Bonn 2025 Matters",
    date: "2025-06-17",
    type: "Article",
    publisher: "LinkedIn",
    summary: "Why the Bonn climate talks shape the next phase of international climate action even though they receive less attention than COP meetings.",
    projectContext: "An independently researched climate-policy explainer written for readers who know the major COP summits but not the technical negotiations that happen between them. The piece turns institutional process into a clear account of why Bonn matters.",
    readingMinutes: 5,
    image: "public/images/work/bonn.webp",
    imageAlt: "Delegates seated at a United Nations climate conference in Bonn",
    tags: ["Sustainability", "Environmental Science", "Article"],
    url: "https://www.linkedin.com/pulse/climate-negotiations-you-havent-heard-why-bonn-2025-matters-shannon-czcac/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "games-for-brands",
    title: "Games for Brands: What to Do, What to Avoid",
    date: "2025-06-16",
    type: "B2B industry article",
    publisher: "Workinman Interactive",
    summary: "A practical guide to brand guidelines, IP constraints, creative approvals, and risk in playable brand experiences.",
    projectContext: "This assignment had to explain why branded games require both creative ambition and disciplined approval systems. Paul organized guidance on brand books, model sheets, color and trademark risk, narrative permissions, review cycles, and audience expectations into a useful do-and-don’t structure. The article was developed with Workinman’s editors, executives, artists, and studio stakeholders, whose briefs and feedback set the technical depth, tone, examples, and client-facing purpose.",
    readingMinutes: 6,
    image: "public/images/work/games-for-brands.webp",
    imageAlt: "Game controller surrounded by colorful brand-approval graphics",
    tags: ["Client Work", "B2B", "Interactive Media", "SEO & Content"],
    url: "https://workinman.com/games-for-brands/",
    linkLabel: "Read on Workinman",
    featured: true
  },
  {
    id: "clean-water-climate-change-habs",
    title: "Think Your Water Is Clean? Climate Change Might Be Proving You Wrong",
    date: "2025-06-12",
    type: "Article",
    publisher: "LinkedIn",
    summary: "What harmful algal blooms can look like, why climate conditions matter, and why apparently clear water is not the whole story.",
    projectContext: "A public-facing science explainer connecting visible bloom warning signs with the less visible relationship among warming water, nutrient loading, and cyanobacterial risk. The assignment demonstrates plain-language risk communication without overstating certainty.",
    readingMinutes: 5,
    image: "public/images/work/algae.webp",
    imageAlt: "Green harmful algal bloom covering the surface of shallow water",
    tags: ["Environmental Science", "Sustainability", "Scientific Communication"],
    url: "https://www.linkedin.com/pulse/think-your-water-clean-climate-change-might-proving-you-paul-shannon-e6bhc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "digital-board-games",
    title: "Making Digital Board Games Feel Real: 8 Tips",
    date: "2025-06-11",
    type: "Industry article",
    publisher: "Workinman Interactive",
    summary: "An eight-part guide to preserving rhythm, agency, atmosphere, solo play, and long-term interest when board games move to screens.",
    projectContext: "The editorial challenge was to explain why a technically faithful digital port can still feel wrong. Paul built an eight-part structure around pacing, setup, interface context, reward feedback, atmosphere, solo play, physical–digital continuity, and live content, using recognizable adaptations as evidence. Workinman’s studio team helped define the outline, examples, voice, and scope; Paul converted that direction into a readable article for publishers, designers, and prospective development partners.",
    readingMinutes: 6,
    image: "public/images/work/digital-board-games.webp",
    imageAlt: "Board-game pieces beside the headline 8 Tips for Making Digital Board Games Feel Real",
    tags: ["Client Work", "Technology", "Interactive Media", "SEO & Content"],
    url: "https://workinman.com/digital-board-games/",
    linkLabel: "Read on Workinman",
    featured: false
  },
  {
    id: "why-freelance-writers-quit",
    title: "Why 90% of Freelance Writers Quit—And How to Be the 10% Who Don’t",
    date: "2025-06-05",
    type: "Article",
    publisher: "LinkedIn",
    summary: "A practical look at the habits and business realities that drive freelancers out—and what makes a writing practice last.",
    projectContext: "Independent professional commentary grounded in Paul’s freelance writing experience. The article reframes persistence as a set of business systems and working habits rather than a motivational slogan.",
    readingMinutes: 5,
    image: "public/images/work/freelance-persistence.webp",
    imageAlt: "Laptop, books, glasses, and notebooks arranged on a freelance writer’s desk",
    tags: ["Freelancing", "Article"],
    url: "https://www.linkedin.com/pulse/why-90-freelance-writers-quitand-how-10-who-dont-paul-shannon-fluxc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "sustainable585-issue-5",
    title: "Sustainable585: Issue #5 — Where the Systems Hold, Quietly",
    date: "2025-06-01",
    type: "Regional dispatch",
    publisher: "LinkedIn",
    summary: "A regional dispatch on environmental research, local projects, and the quieter systems work happening across the 585.",
    projectContext: "Independently researched and published as part of Sustainable585, Paul’s regional environmental dispatch. This issue curates local reporting and projects, then adds concise context for Rochester-area readers.",
    readingMinutes: 6,
    image: "public/images/work/reforestation-seedling.webp",
    imageAlt: "Gloved hands planting a young seedling in forest soil",
    tags: ["Sustainability", "Rochester", "Article"],
    url: "https://www.linkedin.com/pulse/issue-5-june-1-2025-where-systems-hold-quietly-paul-shannon-cgqic/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "freelancers-stay-broke-after-clients",
    title: "Why Most Freelancers Stay Broke Even After Landing Clients",
    date: "2025-05-29",
    type: "Article",
    publisher: "LinkedIn",
    summary: "Landing a client is the start of the work, not the finish line: a look at the systems behind sustainable freelance income.",
    projectContext: "Independent professional commentary examining the less visible work that follows a signed contract: scoping, delivery, cash flow, client retention, and repeatable operating habits.",
    readingMinutes: 4,
    image: "public/images/work/freelance-systems.webp",
    imageAlt: "Freelancer leaning back at a desk while reviewing work on a computer",
    tags: ["Freelancing", "Article"],
    url: "https://www.linkedin.com/pulse/why-most-freelancers-stay-broke-even-after-landing-clients-shannon-1etyc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "elon-musk-mars",
    title: "No, Elon Musk Is Not Bringing Us to Mars",
    date: "2025-05-22",
    type: "Article",
    publisher: "LinkedIn",
    summary: "A critical look at the marketing, infrastructure, and environmental assumptions behind popular promises of Mars settlement.",
    projectContext: "An independently researched technology commentary piece separating the public narrative of Mars settlement from the scientific, infrastructural, and environmental constraints that narrative often leaves out.",
    readingMinutes: 5,
    image: "public/images/work/mars.webp",
    imageAlt: "Blue sunset over the Martian horizon photographed by a NASA rover",
    tags: ["Technology", "Sustainability", "Article"],
    url: "https://www.linkedin.com/pulse/elon-musk-bringing-us-mars-paul-shannon-lrfne/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "sustainable585-issue-4",
    title: "Sustainable585: Issue #4 — Where the Water Rises",
    date: "2025-05-18",
    type: "Regional dispatch",
    publisher: "LinkedIn",
    summary: "A regional roundup tracing sustainability work, local decisions, and changing water conditions across greater Rochester.",
    projectContext: "Independently researched and published as part of Sustainable585, Paul’s regional environmental dispatch. This edition connects high water, local decisions, and community sustainability work across the Rochester region.",
    readingMinutes: 6,
    image: "public/images/work/high-water-flood.webp",
    imageAlt: "Floodwater surrounding a riverside marina and buildings near a raised bridge",
    tags: ["Sustainability", "Rochester", "Article"],
    url: "https://www.linkedin.com/pulse/issue-4-may-18-2025-where-water-rises-paul-shannon-rudlc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "carbon-offsets-insetting",
    title: "Carbon Offsets Are Dead. Long Live Carbon Insetting.",
    date: "2025-05-15",
    type: "Article",
    publisher: "LinkedIn",
    summary: "Why carbon offsets have lost credibility—and why investing inside a company’s own value chain may be more accountable.",
    projectContext: "An independently researched sustainability and business article comparing carbon offsetting with insetting. The editorial challenge was explaining a contested corporate-climate concept without presenting either approach as a universal solution.",
    readingMinutes: 5,
    image: "public/images/work/forest.webp",
    imageAlt: "Aerial view of a dense pine forest",
    tags: ["Sustainability", "B2B", "Article"],
    url: "https://www.linkedin.com/pulse/carbon-offsets-dead-long-live-insetting-paul-shannon-dqqcc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "what-makes-a-good-portfolio",
    title: "What Makes a Good Portfolio? (Hint: It’s Not Just the Work)",
    date: "2025-05-08",
    type: "Article",
    publisher: "LinkedIn",
    summary: "A strong portfolio shows more than clips: it reveals the structure, context, and judgment behind the finished work.",
    projectContext: "Independent professional commentary about portfolio strategy. The piece argues for context, process, and editorial judgment—the same rationale behind the expandable project notes in this portfolio.",
    readingMinutes: 4,
    image: "public/images/work/portfolio-process.webp",
    imageAlt: "Freelancer working on a laptop beside the coast with a notebook and phone",
    tags: ["Freelancing", "SEO & Content", "Article"],
    url: "https://www.linkedin.com/pulse/what-makes-good-portfolio-hint-its-just-work-paul-shannon-yot1c/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "sustainable585-issue-3",
    title: "Sustainable585: Issue #3 — Biweekly Regional Roundup",
    date: "2025-05-04",
    type: "Regional dispatch",
    publisher: "LinkedIn",
    summary: "Earth Day, Arbor Day, heavy rain, and collective sustainability work across the 585 in early May.",
    projectContext: "Independently researched and published as part of Sustainable585, Paul’s regional environmental dispatch. This issue gathers time-sensitive local developments into a coherent biweekly account rather than a loose link list.",
    readingMinutes: 6,
    image: "public/images/work/community-tree-planting.webp",
    imageAlt: "A newly planted tree standing in an open green field",
    tags: ["Sustainability", "Rochester", "Article"],
    url: "https://www.linkedin.com/pulse/issue-3-may-4-2025-biweekly-regional-roundup-paul-shannon-c6xic/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "ai-corporate-sustainability",
    title: "How Artificial Intelligence Is Reshaping Corporate Sustainability",
    date: "2025-05-01",
    type: "Article",
    publisher: "LinkedIn",
    summary: "AI has environmental costs, but it is also changing how companies measure, model, and manage sustainability work.",
    projectContext: "An independently researched B2B explainer balancing AI’s environmental costs against its emerging uses in sustainability measurement and decision-making. The piece is structured for non-specialist business readers.",
    readingMinutes: 5,
    image: "public/images/work/servers.webp",
    imageAlt: "Rows of illuminated server racks in a data center",
    tags: ["Technology", "Sustainability", "B2B"],
    url: "https://www.linkedin.com/pulse/how-artificial-intelligence-reshaping-corporate-paul-shannon-yqdsc",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "smart-thermostat-wont-save-you",
    title: "I’m Sorry, but Your Smart Thermostat Won’t Save You",
    date: "2025-04-24",
    type: "Article",
    publisher: "LinkedIn",
    summary: "Consumer devices can reduce energy use, but they cannot substitute for the systemic changes climate policy requires.",
    projectContext: "An independently researched climate commentary piece using the smart thermostat as a concrete example of a larger distinction: individual efficiency measures can help, but they cannot replace policy and infrastructure change.",
    readingMinutes: 4,
    image: "public/images/work/thermostat.webp",
    imageAlt: "Digital smart thermostat mounted on a white wall",
    tags: ["Technology", "Sustainability", "Article"],
    url: "https://www.linkedin.com/pulse/your-smart-thermostat-wont-save-you-paul-shannon-vkwoc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "rochester-sustainable-fashion-brands",
    title: "Beyond Fast Fashion — Five Rochester Brands Leading the Local Sustainability Movement",
    date: "2025-04-22",
    type: "Article",
    publisher: "LinkedIn",
    summary: "A look at five Rochester-area businesses approaching clothing, materials, and local sustainability differently.",
    projectContext: "An independently researched local-business article identifying Rochester-area alternatives to fast fashion. Paul combined regional discovery with sustainability context and concise profiles for a general audience.",
    readingMinutes: 6,
    image: "public/images/work/fashion.webp",
    imageAlt: "Rows of clothing and luggage inside a retail store",
    tags: ["Sustainability", "Rochester", "Article"],
    url: "https://www.linkedin.com/pulse/beyond-fast-fashion-five-rochester-brands-leading-local-paul-shannon-06uoe/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "sustainable585-issue-2",
    title: "Sustainable585: Issue #2 — Where the Work Begins",
    date: "2025-04-20",
    type: "Regional dispatch",
    publisher: "LinkedIn",
    summary: "A look at how practical sustainability work begins in the 585—quietly, locally, and one committed step at a time.",
    projectContext: "Independently researched and published as part of Sustainable585, Paul’s regional environmental dispatch. This issue focuses on early-stage local work and the institutions and people moving it forward.",
    readingMinutes: 6,
    image: "public/images/work/spring-seedlings.webp",
    imageAlt: "Volunteers tending young seedlings in a community planting area",
    tags: ["Sustainability", "Rochester", "Article"],
    url: "https://www.linkedin.com/pulse/issue-1-april-13-2025-where-spring-begins-paul-shannon-jtxmc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "katy-perry-spaceflight-climate",
    title: "How Much Did Katy Perry’s Rocket Ride Really Cost the Climate?",
    date: "2025-04-17",
    type: "Article",
    publisher: "LinkedIn",
    summary: "A closer look at the environmental footprint behind a brief celebrity spaceflight and the spectacle surrounding it.",
    projectContext: "An independently researched science-and-culture article using a high-profile spaceflight to explain emissions, scale, and the difference between a visually dramatic event and its wider climate context.",
    readingMinutes: 4,
    image: "public/images/work/rocket.webp",
    imageAlt: "Space shuttle Columbia launching through bright clouds",
    tags: ["Technology", "Sustainability", "Scientific Communication"],
    url: "https://www.linkedin.com/pulse/how-much-did-katy-perrys-rocket-ride-really-cost-climate-paul-shannon-u0zve/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "sustainable585-issue-1",
    title: "Sustainable585: Issue #1 — Where Spring Begins",
    date: "2025-04-13",
    type: "Regional dispatch",
    publisher: "LinkedIn",
    summary: "The first Sustainable585 dispatch: a recurring environmental roundup focused on the greater Rochester region.",
    projectContext: "The first independently researched Sustainable585 regional dispatch. Paul established the series format, selected local developments, and supplied the connective context needed to make a recurring roundup useful.",
    readingMinutes: 5,
    image: "public/images/work/rochester.webp",
    imageAlt: "Genesee River and downtown Rochester under a blue sky",
    tags: ["Sustainability", "Rochester", "Article"],
    url: "https://www.linkedin.com/pulse/issue-1-april-13-2025-where-spring-begins-paul-shannon-jtxmc/",
    linkLabel: "Read on LinkedIn",
    featured: false
  },
  {
    id: "climate-change-harmful-algal-blooms-genesee-finger-lakes",
    title: "The Impact of Climate Change on Harmful Algal Blooms in the Genesee–Finger Lakes Region",
    date: "2025-01-01",
    datePrecision: "year",
    type: "Regional research report",
    publisher: "Climate Solutions Accelerator",
    summary: "A nine-county review connecting harmful algal bloom reports with precipitation, temperature, lake history, and watershed runoff conditions.",
    projectContext: "Conducted for the Climate Solutions Accelerator in the Genesee–Finger Lakes region. Paul reviewed nine New York counties and analyzed NYSDEC bloom records alongside NOAA precipitation and temperature data, then communicated patterns, projections, and important limits without treating correlation as causation.",
    readingMinutes: 24,
    image: "public/images/work/lake-erie-hab.webp",
    imageAlt: "A green-blue algal bloom lining the shore of Lake Erie",
    tags: ["Environmental Science", "Research", "Scientific Communication", "Rochester"],
    url: "public/downloads/climate-change-habs-genesee-finger-lakes.pdf",
    linkLabel: "Read the research report",
    featured: true
  },
  {
    id: "5-tips-for-gamifying-boring-apps",
    title: "5 Tips for Gamifying Even the Most Boring App",
    date: "2025-01-01",
    datePrecision: "year",
    type: "Industry article",
    publisher: "Workinman Interactive",
    summary: "How progression, habit loops, achievements, competition, and surprise can make utility apps more engaging.",
    projectContext: "Written for product owners whose useful apps struggle to hold attention, this piece translates game-design practice into five implementable systems: progression, daily loops, achievements, social competition, and small moments of surprise. Paul worked from Workinman’s approved direction and studio expertise, coordinating with editors, executives, artists, and contributors to keep examples relevant across corporate tools, commerce, health, and service applications rather than treating gamification as decoration.",
    readingMinutes: 5,
    image: "public/images/work/gamifying-boring-apps.webp",
    imageAlt: "Person holding a phone beside the headline 5 Tips for Gamifying Even the Most Boring App",
    tags: ["Client Work", "Technology", "Interactive Media", "SEO & Content"],
    url: "https://workinman.com/5-tips-for-gamifying-boring-apps/",
    linkLabel: "Read on Workinman",
    featured: false
  },
  {
    id: "noovie-trivia-app",
    title: "Why Noovie Trivia Is More Than (Just) a Quiz App",
    date: "2025-01-01",
    datePrecision: "year",
    type: "Product-focused article",
    publisher: "Workinman Interactive",
    summary: "A product story explaining how game modes, fresh content, social play, and real-world rewards extend moviegoing beyond the theater.",
    projectContext: "This product-focused story had to do more than list trivia modes. Paul framed Noovie Trivia around the moviegoing ritual, then connected its breadth of film content, solo and multiplayer play, daily updates, leaderboards, and ticket-prize loop to replayability and cinema culture. Workinman’s product and editorial stakeholders supplied the feature priorities and review; Paul shaped them into an audience-centered narrative for movie fans and prospective interactive-media clients.",
    readingMinutes: 4,
    image: "public/images/work/noovie-trivia-app.webp",
    imageAlt: "Noovie Trivia graphics with popcorn and a movie theater screen",
    tags: ["Client Work", "Technology", "Interactive Media", "B2B"],
    url: "https://workinman.com/noovie-trivia-app/",
    linkLabel: "Read on Workinman",
    featured: false
  },
  {
    id: "museums-relevant-with-digital-exhibits",
    title: "Designing Digital Museum Exhibits That Visitors Actually Remember",
    date: "2025-01-01",
    datePrecision: "year",
    type: "Industry article",
    publisher: "Workinman Interactive",
    summary: "A guide to memorable museum experiences built through play, physical interaction, continuity, and responsive environments.",
    projectContext: "Aimed at curators, museum leaders, and exhibit partners, this article explains how game mechanics, mobile extensions, physical interaction, camera-aware design, projection mapping, and modular content can make digital exhibits more memorable. Paul organized Workinman’s exhibit examples into a clear progression from learning to longevity, collaborating with creative leads, editors, executives, artists, and technical contributors who supplied project details and shaped the article’s scope.",
    readingMinutes: 6,
    image: "public/images/work/digital-museum-exhibits.webp",
    imageAlt: "Visitor using an interactive table beside illuminated museum displays",
    tags: ["Client Work", "Technology", "Interactive Media", "Education & Community"],
    url: "https://workinman.com/museums-relevant-with-digital-exhibits/",
    linkLabel: "Read on Workinman",
    featured: false
  },
  {
    id: "rhizofiltration-microcystis-water-hyacinth",
    title: "Rhizofiltration of an Induced Microcystis Bloom Using Water Hyacinth",
    date: "2024-01-01",
    datePrecision: "year",
    type: "Experimental research paper",
    publisher: "University at Albany",
    summary: "A constructed-wetland experiment testing whether water hyacinth could remove bloom-supporting nutrients from an induced Microcystis system.",
    projectContext: "Conducted at Hudson Falls High School through the University at Albany Science Research in the High School program. Paul designed and documented a constructed-wetland model, induced a Microcystis bloom, introduced water hyacinth for rhizofiltration, and tracked water-quality measurements while clearly reporting the study’s constraints.",
    readingMinutes: 18,
    image: "public/images/work/hyacinth.webp",
    imageAlt: "Close-up of pale water hyacinth roots suspended in water",
    tags: ["Environmental Science", "Research", "Scientific Communication"],
    url: "public/downloads/rhizofiltration-microcystis-water-hyacinth.pdf",
    linkLabel: "Read the research paper",
    featured: true
  },
  {
    id: "engin-ukraine-connections",
    title: "ENGin: Rebuilding Ukraine Through 1-on-1 Connections",
    date: "2023-01-02",
    type: "Article",
    publisher: "Medium",
    summary: "How ENGin creates one-to-one English-language connections for Ukrainians—and how volunteers can become involved.",
    projectContext: "An early service-focused article explaining ENGin’s one-to-one language-partner model and turning organizational information into a clear invitation for prospective volunteers.",
    readingMinutes: 4,
    image: "public/images/work/ukraine.webp",
    imageAlt: "People carrying Ukrainian flags during an Independence Day gathering",
    tags: ["Education & Community", "Article"],
    url: "https://medium.com/@pshannon.2021/engin-rebuilding-ukraine-through-1-on-1-connections-b742752a22ea",
    linkLabel: "Read on Medium",
    featured: false
  }
];
